name: Build and Release Plugin

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true
        default: 'v1.0.0'
      
permissions:
  contents: write  # required to create release/upload files

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build plugin assets
        run: npm run build
        
      - name: Create plugin directory
        run: mkdir -p vine-poster-plugin
        
      - name: Copy plugin files to directory
        run: |
          cp plugin.php vine-poster-plugin/
          cp -r build vine-poster-plugin/
          cp -r assets vine-poster-plugin/
          
      - name: Create plugin zip
        run: |
          cd vine-poster-plugin
          zip -r ../vine-poster-plugin.zip . -x "*.DS_Store" "node_modules/*" "*.log"
          cd ..
          
      - name: Get tag name and create tag if needed
        id: get_tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG_NAME="${{ github.event.inputs.tag_name }}"
            echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
            # Create tag if it doesn't exist (for manual runs)
            if ! git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"
              git tag "$TAG_NAME"
              git push origin "$TAG_NAME"
            fi
          else
            echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi
          
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.get_tag.outputs.tag_name }} \
            --title "Vine Poster Plugin ${{ steps.get_tag.outputs.tag_name }}" \
            --notes "## Vine Poster Editor Plugin Release

          This release contains:
          - \`vine-poster-plugin.zip\` - Complete WordPress plugin package
          - \`index.html\` - Standalone demo/playground file

          ### Installation
          1. Download \`vine-poster-plugin.zip\`
          2. Upload to your WordPress site via Plugins > Add New > Upload Plugin
          3. Activate the plugin

          ### Demo
          Access the standalone demo by downloading \`index.html\` or visiting the direct link from this repository." \
            vine-poster-plugin.zip \
            index.html