name: Build and Deploy Plugin

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build plugin assets
        run: npm run build
        
      - name: Create plugin directory
        run: mkdir -p vine-poster-plugin
        
      - name: Copy plugin files to directory
        run: |
          cp plugin.php vine-poster-plugin/
          cp -r build vine-poster-plugin/
          
      - name: Create plugin zip
        run: |
          cd vine-poster-plugin
          zip -r ../plugin.zip . -x "*.DS_Store" "node_modules/*" "*.log"
          cd ..
          
          
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy to Remote Server
        run: |
          # Copy plugin zip file
          scp plugin.zip ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:public_html/vine-poster-editor/
          
          # Copy index.html file
          scp index.html ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:public_html/vine-poster-editor/
          
          echo "Files deployed successfully to public_html/vine-poster-editor/"
          echo "Plugin zip: https://${{ secrets.SSH_HOST }}/vine-poster-editor/plugin.zip"
          echo "Demo page: https://${{ secrets.SSH_HOST }}/vine-poster-editor/index.html"
